language: python
python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5
 - 3.6

# Use container-based infrastructure
sudo: false

install:
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

 # Coverage 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install "coverage<4"; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

script:
 - coverage run --source=olefile -m nose tests

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes .
 - pep8 --statistics --count .

matrix:
  fast_finish: true
